name: Run Automation Script

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run TestNG tests
      run: |
        # Set up the browser driver (e.g., for Chrome)
        CHROME_VERSION=$(google-chrome --version | grep -oP "(?<=Google Chrome )[\d.]+")
        CHROME_DRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
        curl -s "https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip" -o chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        chmod +x chromedriver
        sudo mv chromedriver /usr/local/bin/chromedriver

        # Run the TestNG tests with a visible browser
        mvn test -Dsurefire.suiteXmlFiles=testng.xml
