name: Run Maven Tests
'on':
  push:
    branches:
      - main
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: '11'
      - name: Run TestNG Tests
        run: mvn -B test -Dsurefire.suiteXmlFiles=testng.xml
      - name: Run Selenium Tests
        id: test-results
        run: |
        # Your commands to run Selenium tests and generate reports
        # e.g., mvn test

      - name: Archive Test Reports
        uses: actions/upload-artifact@v2
        with:
         name: test-reports
         path: test-output/emailable-report.html

      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v2
        with:
            server_address: smtp.gmail.com
            server_port: 587
            username: ${{ secrets.VIGNESH }}
            password: ${{ secrets.PASSWORD }}
            subject: 'Selenium Test Results'
            from: 'vignesh.g@trackdfect.com'
            body: |
              The Selenium tests have completed.

              Test Summary:
              - Passed: ${{ steps.test-results.outputs.passed }}
               - Failed: ${{ steps.test-results.outputs.failed }}

                Check the test reports for details.
              to: sarath.s@trackdfect.com
