name: Run Maven Tests
'on':
  push:
    branches:
      - main
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: '11'
      - name: Run TestNG Tests
        run: mvn -B test -Dsurefire.suiteXmlFiles=testng.xml
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.example.com
          server_port: 587
          username: ${{ secrets.VIGNESH }}
          password: ${{ secrets.PASSWORD }}
          subject: "Selenium Test Results"
          to: sarath.s@trackdfect.com
          from: vignesh.g@trackdfect.com
          body: |
            The Selenium test execution has completed.
